### ISSUE TITLE
네이버 뉴스 검색시 정렬기준 선택 불가 현상

### ISSUE THREAD

**Issue by gamjaa** [joyfuI/search-link-fix#1]
https://search.naver.com/search.naver?where=news&sm=tab_jum&query=뉴스
네이버 뉴스 검색 페이지에서 '관련도순', '최근순', '오래된순' 버튼이 동작하지 않는 문제가 있습니다.
확인 부탁드립니다.

**Comment by joyfuI** [comment]
확인하고 수정했습니다. 업데이트 해주세요.
버그제보 감사합니다.
