### ISSUE TITLE
다음 검색 페이지 우측 실시간 뉴스 검색어 탭 선택 불가

### ISSUE THREAD

**Issue by gamjaa** [joyfuI/search-link-fix#2]
![image](https://user-images.githubusercontent.com/6895992/55285348-fb84f180-53c4-11e9-8fca-cadf3ca0adfc.png)
다음 검색 페이지 우측의 실시간 뉴스 검색어에서 '종합', '연예', '스포츠' 탭 선택이 동작하지 않습니다.
확인 부탁드립니다. 감사합니다.

**Comment by joyfuI** [comment]
수정해서 새버전으로 업데이트 했습니다.  
버그제보 감사합니다.
